import Link from "next/link";
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="pt-BR">
      <body className={`${jetBrainsMono.className} bg-zinc-950 text-white`}>
        <div className="w-full min-h-screen flex flex-col">
          <header className="w-full flex items-center justify-center p-4 gap-6 sticky top-0 bg-zinc-950 bg-opacity-75 border-b border-zinc-950 backdrop-blur-lg backdrop-saturate-100">
            <Link href="/" className="hover:underline underline-offset-4">
              Cronômetro
            </Link>
            <Link href="/tasks" className="hover:underline underline-offset-4">
              Tarefas
            </Link>
          </header>
          <main className="w-full h-full flex-grow flex flex-col items-center justify-center p-8 gap-2">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
